### PR TITLE
Create ru_RU.lang

### PR DESCRIPTION
**Pull request by labpaw**
Some names sounds really derpy, they will be improved over time :)
Translated with help of @fewizz

Also, is [this](https://github.com/ganymedes01/TheErebus/blob/master/src/main/resources/assets/erebus/lang/en_US.lang#L251) intentional? Shouldn't this be mudbrick?

### CODE REVIEW

**Comment by ganymedes01** [comment]
It's Mirbrick.
No idea what it means. It was named by @Dylan4ever =P

**Comment by Adaptivity** [comment]
How I should translate it @Dylan4ever? Any suggestions?

**Comment by Adaptivity** [comment]
Also, @3TUSK might be interested in translating The Erebus into Chinese.

**Comment by 3TUSK** [comment]
@Adaptivity Well the problem is that I haven't played with The Erebus mod.

**Pull request merged**
