### PR TITLE
Tried to make oregen disableable and failed

### PR DESCRIPTION
**Pull request by RCXcrafter**
I tried to make it possible to disable the generation of vanilla erebus ores because I needed that for my modpack. However I have failed since the ores still generate (I was not able to confirm this for lapis and diamond).

### CODE REVIEW

**Comment by ganymedes01** [comment]
-What's the PR for then if you said it yourself that it doesn't do what it's intended?
-Are you aware that disabling some of the Erebus ores will make several parts of the mod uncraftable?
-I can add the config options myself if you can elaborate more on why you need them :)

**Comment by RCXcrafter** [comment]
- Well, I was hoping to get some help from you, I should have probably asked for help then. Help?
- I am fully aware of that, I wanted to use another mod to generate the ores for me instead, it's mostly for the sake of consistency since the default spawn rates aren't unbalanced or something.
- So, I need them for my modpack. I want to use WTFOres to generate all of my ores, it can generate ores in any stone type (a bridge mod will be needed for stones that aren't included by default) and it can generate ores in different densities.

Could you also tell me what I'm doing wrong?

**Comment by vadis365** [comment]
yeah...um... that isn't how I would do it.
you may well have made options to turn off and on your boolean... but you are not turning the Erebus code off anywhere.
I would personally scrap what you have done here and wait for one of the dev team to add it in a future update - like I have said previously.

**Comment by RCXcrafter** [comment]
This was the only oregen code I could find, where is this erebus code you're talking about? I'm sorry if I'm annoying you, as you can probably tell I don't have a lot of coding experience.

**Comment by ganymedes01** [comment]
I'm not annoied, sorry if I sound harsh, I don't mean to.

The ore gen code is all over the place and is considerably more complex than most mod's because we generate ores based on biomes as well as Y-Level.

I'll see how difficult it would be to allow turning specific ores off, but bare in mind you're probably not going to be able to reproduce the exact behaviour using a third mod.

**Comment by RCXcrafter** [comment]
You didn't sound harsh, I just thought I might be annoying you with this.
I think I can actually get pretty close to your behaviour. The mod I use can spawn X times more of an ore when it's in a certain biome and it can restrict ores to a certain depth (it checks the average height of a chunk).
This is the mod I'm using:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2365907

**Comment by RCXcrafter** [comment]
I just had a look at the biomes code and I think I'll be able to get everything working. Unless you really want to do it yourself.

**Pull request closed without merging**
