### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by labpaw**
Added missing honey block and dragonfly spawner localization to en_US.lang. Also, changed grey to gray. (since it's US lang file)

### CODE REVIEW

**Comment by ganymedes01** [comment]
Thank you :)
The lang file is really messy, I think there's a bunch of entries in there that aren't used anymore. We really need to get around to organising it XD

**Comment by Adaptivity** [comment]
Yeah, I agree. Also, names like "tile.erebus.wallErebus_0" should be changed to something like "tile.erebus.wall_umberstone" and etc.

**Comment by ganymedes01** [comment]
Indeed!
Fixing all that is easy but it takes a long time and is boring. That's why I haven't gotten around to it yet XD

**Comment by Adaptivity** [comment]
I understand. Tons of copy-paste work :smile:

**Comment by vadis365** [comment]
Also missing are all the glowshroom component parts... looks horrible using WALIA.
animated chest, animated bamboo crate and animated petrified crafting tables are all missing entity localisation naming too (my fault probably :P )

**Comment by ganymedes01** [comment]
That's your fault for giving them different names =P
Just because they have different metas doesn't mean they need a name for each meta value. Look at the furnace for example, different metas, same name.

**Comment by vadis365** [comment]
They are not different metas - they are different blocks.
was made when all the 1.8 scaremongering about meta removal was rife :P

**Comment by ganymedes01** [comment]
Oh my... okay I'm messing with those classes tonight.

**Comment by vadis365** [comment]
according to the git history - I have never touched those files - lol
https://github.com/ganymedes01/TheErebus/commits/master/src/main/java/erebus/block/glowshroom/BlockGlowshroomStalkDown1.java
I seem to remember making the glowshrooms though... must have bben in a past life.

**Comment by vadis365** [comment]
Requesting a UK Lang file please :P
"Added missing honey block and dragonfly spawner localization to en_US.lang. Also, changed grey to gray. (since it's US lang file)"

**Comment by Adaptivity** [comment]
@vadis365 you can just create en_GB.lang and add only stuff that you want to change (such as gray -> grey).

**Comment by vadis365** [comment]
@Adaptivity - I was having a joke ;)

**Pull request merged**
